### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by job-talk** [job-talk/rajatrucking#4]
Images/Iconography 
  - [x] Add more images to carousel
  - [x] Create logo/badges for brand
  - [x] Redesign favicon

Mobile
  - [x] Redesign Slideout Menu (for inspiration: https://slideout.js.org/)

Site's Text Content
  - [x] Improve site's text content

**Comment by job-talk** [comment]
- [ ] Add srcset/lazyloading/progressive loading for index images
